_wandb:
    value:
        cli_version: 0.21.1
        e:
            ds8nd4uhu1h9gdrfhxk94n8gmosrqhu3:
                codePath: api\main.py
                codePathLocal: api\main.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "1022870155264"
                        used: "751936180224"
                email: pete@twinchutes.io
                executable: C:\Users\Pete\AppData\Local\Programs\Python\Python311\python.exe
                git:
                    commit: 9d2802f325bec384649569523f4a4d07837af15f
                    remote: https://github.com/uelski/4705_final.git
                gpu: NVIDIA GeForce RTX 3070 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 5120
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce RTX 3070 Laptop GPU
                      uuid: GPU-df2e7264-49eb-9c4a-5c89-b5fd06aaa63b
                host: LAPTOP-VGLQBRBG
                memory:
                    total: "17024741376"
                os: Windows-10-10.0.26100-SP0
                program: c:\Users\Pete\comp_4705\4705_final\api\main.py
                python: CPython 3.11.1
                root: C:\Users\Pete\comp_4705\4705_final
                startedAt: "2025-08-19T22:53:33.921653Z"
                writerId: ds8nd4uhu1h9gdrfhxk94n8gmosrqhu3
        m: []
        python_version: 3.11.1
        t:
            "1":
                - 53
            "2":
                - 53
            "4": 3.11.1
            "5": 0.21.1
            "8":
                - 3
            "12": 0.21.1
            "13": windows-amd64
